version: "3.8"
services:
  postfix:
    build: .
    ports:
      - "25:25"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - MYDOMAIN=${MYDOMAIN}
      - CUSTOM_HEADER=${CUSTOM_HEADER}
      - RELAYHOST=${RELAYHOST}
      - TRANSPORT=${TRANSPORT}
      - SASL_ENABLE=${SASL_ENABLE}
      - SASL_PASSWD=${SASL_PASSWD}