version: "3.8"
services:
  postfix:
    build: .
    ports:
      - "25:25"
    environment:
      # AWS
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      # Postfix
      - CUSTOM_HEADER=${CUSTOM_HEADER}
      - ENVELOPE_FROM=${ENVELOPE_FROM}
      - MYDOMAIN=${MYDOMAIN}
      - MYNETWORKS=${MYNETWORKS}
      - RELAYHOST=${RELAYHOST}
      - SASL_ENABLE=${SASL_ENABLE}
      - SASL_PASSWD=${SASL_PASSWD}
      - TRANSPORT=${TRANSPORT}
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
