version: "3.8"
services:
  postfix:
    build: .
    ports:
      - "25:25"
    environment:
      - MYDOMAIN=${MYDOMAIN}
      - CUSTOM_HEADER=${CUSTOM_HEADER}
      - RELAYHOST=${RELAYHOST}
      - SASL_ENABLE=${SASL_ENABLE}
      - SASL_PASSWD=${SASL_PASSWD}